name: build
on:
  pull_request:
    types: [opened, synchronize]
# slack通知する場合
# env:
#  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.15.x]
    steps:
      - uses: actions/checkout@v1
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn
      - name: Run build
        run: yarn run build
# slack通知する場合
#      # テスト失敗時はこちらのステップが実行される
#      - name: Slack Notification on Failure
#        uses: rtCamp/action-slack-notify@v2.0.2
#        if: failure()
#        env:
#          SLACK_CHANNEL: front-end-git-notice
#          SLACK_TITLE: BUILD Failure
#          SLACK_MESSAGE: 'BUILD が失敗しましたので確認してください:eyes:'
#          SLACK_COLOR: danger
